DROP TABLE IF EXISTS task;


CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL
);